"""empty message

Revision ID: 1fd4f1efd228
Revises: 
Create Date: 2023-04-07 20:50:10.687692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd4f1efd228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('human_size', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('webp', 'jpeg', 'tiff', 'bmp', 'png', name='types'), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('browser_metadata', sa.JSON(), nullable=True),
    sa.Column('filepath', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__images')),
    sa.UniqueConstraint('filename', name=op.f('uq__images__filename'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
